### ISSUE TITLE
Investigate caching issue on Dreamhost deployment

### ISSUE THREAD

**Issue by fluffy-critter** [fluffy-critter/Publ#30]
## Expected Behavior

When a page or its dependencies is updated, it should be reflected after an amount of time.

## Current Behavior

On Dreamhost, prior responses seem to be cached indefinitely.

## Possible Solution

Probably a matter of setting `response.headers['Cache-Control']`; see [these potential solutions](https://stackoverflow.com/questions/34066804/disabling-caching-in-flask). It is unclear if this caching is occurring in Flask or in Passenger (probably the latter).

**Comment by fluffy-critter** [comment]
Verified that it's definitely a problem *after* the Flask stack; I created [a new entry](http://publ.beesbuzz.biz/tests/345-How-long-does-it-take-this-to-show-up) which should appear as a sibling to the [image rendition test](http://publ.beesbuzz.biz/tests/336-Test-of-image-renditions). While the entry itself renders, it doesn't appear in the index or in the previous test.

However, I verified that the entry is available to the templating system from the command line:

```
bibb[~/publ.beesbuzz.biz] (master) plaidfluff$ pipenv run python3
Python 3.6.4 (default, Feb  6 2018, 23:06:37) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from publ import entry
>>> entry.Entry(336)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plaidfluff/publ.beesbuzz.biz/publ/entry.py", line 29, in __init__
    self.date = arrow.get(record.entry_date)
AttributeError: 'int' object has no attribute 'entry_date'
>>> from publ import model
>>> e=entry.Entry(model.Entry.get(model.Entry.id==336))
>>> e
<publ.entry.Entry object at 0x2d228ca9c88>
>>> e.title
'Test of image renditions'
>>> e.id
336
>>> e.next
<publ.utils.CallableProxy object at 0x2d23761a438>
>>> e.next()
<publ.entry.Entry object at 0x2d228c46128>
>>> e.next.title
'How long does it take this to show up?'
>>> e.next.id
345
>>> 
```

So obviously if the template were being rendered it would be getting the new sibling.

I created the new entry at 2018-04-07 23:38:23-07:00; it is not yet showing up in the tests index or feed. No cache-control header is being sent:

```
HTTP/1.1 200 OK
Date: Sun, 08 Apr 2018 06:54:54 GMT
Server: Apache
X-Powered-By: Phusion Passenger 4.0.60
Content-Length: 6242
Status: 200 OK
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>

<feed xmlns="http://www.w3.org/2005/Atom">

    <title>Publ</title>
    <subtitle>A personal publishing system for the modern web</subtitle>
    <link href="http://publ.beesbuzz.biz/tests/feed" rel="self" />
    <link href="http://publ.beesbuzz.biz/tests/" />
    <id>tag:publ.beesbuzz.biz,2018-04-05:tests</id>
    <updated>2018-04-05T12:40:17.674931-07:00</updated>

    
    <entry>
        <title>Test of image renditions</title>
        <link href="http://publ.beesbuzz.biz/tests/336-Test-of-image-renditions" rel="alternate" type="text/html" />
        <updated>2018-04-05T12:40:17.674931-07:00</updated>
        <id>urn:uuid:a28a68eb-c668-4fb8-9d3a-6cbcc3920772</id>
        <content type="html">
<![CDATA[
            <p>Image rendition tests</p>

            
            <a href="/tests/336-Test-of-image-renditions">Read more...</a>
            
]]>
        </content>
        <author>
            <name>fluffy</name>
        </author>
    </entry>
```

so I am guessing that Passenger is deciding that lack of cache-control means "cache it for as long as the process stays active." In the morning I will see if the feed and/or category index have updated.

**Comment by fluffy-critter** [comment]
I didn't do any pinging to see when it started appearing but at 01:49-07:00 the next day it did appear, so the default cache duration is no more than 2 hours, for whatever that's worth.

In any case, the actual cache time should probably be configurable (ideally at the template level - perhaps that's something that could be put into a Jinja tag?), and there should definitely be some sort of cachebusting thing.

**Comment by fluffy-critter** [comment]
Ah, turns out I had FeedOnFeeds' debug log enabled, so I know that the item appeared sometime between 08:00+0000 and 08:10+0000, so that's around 01:10-0700, i.e. a 90-minute TTL on the cache. Good to know.

**Comment by fluffy-critter** [comment]
Looks like the cache duration is just random, possibly indefinite. I added another entry which didn't appear until I manually restarted Passenger.

**Comment by fluffy-critter** [comment]
Just adding *any* cache-control header seems to make Passenger happy. Well then.

**Comment by fluffy-critter** [comment]
And it turns out that while it was *technically* a caching bug, it had [absolutely nothing to do with the fronting service](http://publ.beesbuzz.biz/225). Oops.
